---
abstract: 'A comprehensive, DWIM-featured API to MetaCPAN'
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::Fatal: 0
  Test::More: 0
  Test::TinyMocker: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200009, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MetaCPAN-API
requires:
  Any::Moose: 0
  Carp: 0
  HTTP::Tiny: 0
  JSON: 0
  Try::Tiny: 0
  URI::Escape: 0
version: 0.34
