---
abstract: 'A comprehensive, DWIM-featured API to MetaCPAN'
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::Fatal: 0
  Test::More: 0
  Test::TinyMocker: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MetaCPAN-API
requires:
  Any::Moose: 0
  Carp: 0
  HTTP::Tiny: 0
  JSON: 0
  Try::Tiny: 0
  URI::Escape: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/xsawyerx/metacpan-api.git
version: 0.43
